const USER = {
  PRODUCTION: {
    HOST: '',
    USER: '',
    PWD: '',
  },
  DEVELOPMENT: {
    HOST: 'localhost',
    USER: 'root',
    PWD: '123456',
  }
}

const DATABASE = 'HOME';
const LINK_TABLE = 'LINK';
const SOURCE_TABLE = 'SOURCE';

const DROP_DATABASE = `DROP DATABASE IF EXISTS ${DATABASE};`;
const CREATE_DATABASE = `CREATE DATABASE IF NOT EXISTS ${DATABASE};`;
const CHECK_DATABASE_EXIST = `SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DATABASE}';`;

const CREATE_SOURCE_TABLE = `CREATE TABLE ${SOURCE_TABLE} (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL, 
  insert_date DATE NOT NULL
);`;
const CREATE_LINK_TABLE = `CREATE TABLE ${LINK_TABLE} (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL, 
  link TEXT NOT NULL,
  source_id int(4)  NOT NULL,
  insert_date DATE NOT NULL,
  foreign key(source_id) references ${SOURCE_TABLE}(id)
);`;


module.exports = {
  DATABASE,
  DROP_DATABASE,
  CREATE_DATABASE,
  CHECK_DATABASE_EXIST,
  CREATE_LINK_TABLE,
  CREATE_SOURCE_TABLE
};